import Foundation

/// 百家姓数据：包含常见复姓与单姓，每个姓附带普通话拼音（带声调）。
/// 数据为代码内置，无需外部 JSON。
struct ChineseSurname: Hashable {
    let character: String   // 单字 / 复姓字符串，如 "赵" / "欧阳"
    let pinyin: String      // 拼音（首字母大写），如 "Zhào" / "Ōuyáng"
}

enum SurnameCatalog {
    /// 常见单姓 + 部分复姓。第一版收录约 120 个最高频姓氏，足够支撑配对玩法
    /// （每关随机抽 6–8 对）。后续可扩到 568 全姓。
    static let all: [ChineseSurname] = [
        // 《百家姓》开头
        ChineseSurname(character: "赵", pinyin: "Zhào"),
        ChineseSurname(character: "钱", pinyin: "Qián"),
        ChineseSurname(character: "孙", pinyin: "Sūn"),
        ChineseSurname(character: "李", pinyin: "Lǐ"),
        ChineseSurname(character: "周", pinyin: "Zhōu"),
        ChineseSurname(character: "吴", pinyin: "Wú"),
        ChineseSurname(character: "郑", pinyin: "Zhèng"),
        ChineseSurname(character: "王", pinyin: "Wáng"),
        ChineseSurname(character: "冯", pinyin: "Féng"),
        ChineseSurname(character: "陈", pinyin: "Chén"),
        ChineseSurname(character: "褚", pinyin: "Chǔ"),
        ChineseSurname(character: "卫", pinyin: "Wèi"),
        ChineseSurname(character: "蒋", pinyin: "Jiǎng"),
        ChineseSurname(character: "沈", pinyin: "Shěn"),
        ChineseSurname(character: "韩", pinyin: "Hán"),
        ChineseSurname(character: "杨", pinyin: "Yáng"),
        ChineseSurname(character: "朱", pinyin: "Zhū"),
        ChineseSurname(character: "秦", pinyin: "Qín"),
        ChineseSurname(character: "尤", pinyin: "Yóu"),
        ChineseSurname(character: "许", pinyin: "Xǔ"),
        ChineseSurname(character: "何", pinyin: "Hé"),
        ChineseSurname(character: "吕", pinyin: "Lǚ"),
        ChineseSurname(character: "施", pinyin: "Shī"),
        ChineseSurname(character: "张", pinyin: "Zhāng"),
        ChineseSurname(character: "孔", pinyin: "Kǒng"),
        ChineseSurname(character: "曹", pinyin: "Cáo"),
        ChineseSurname(character: "严", pinyin: "Yán"),
        ChineseSurname(character: "华", pinyin: "Huà"),
        ChineseSurname(character: "金", pinyin: "Jīn"),
        ChineseSurname(character: "魏", pinyin: "Wèi"),
        ChineseSurname(character: "陶", pinyin: "Táo"),
        ChineseSurname(character: "姜", pinyin: "Jiāng"),
        ChineseSurname(character: "戚", pinyin: "Qī"),
        ChineseSurname(character: "谢", pinyin: "Xiè"),
        ChineseSurname(character: "邹", pinyin: "Zōu"),
        ChineseSurname(character: "喻", pinyin: "Yù"),
        ChineseSurname(character: "柏", pinyin: "Bǎi"),
        ChineseSurname(character: "水", pinyin: "Shuǐ"),
        ChineseSurname(character: "窦", pinyin: "Dòu"),
        ChineseSurname(character: "章", pinyin: "Zhāng"),
        ChineseSurname(character: "云", pinyin: "Yún"),
        ChineseSurname(character: "苏", pinyin: "Sū"),
        ChineseSurname(character: "潘", pinyin: "Pān"),
        ChineseSurname(character: "葛", pinyin: "Gě"),
        ChineseSurname(character: "范", pinyin: "Fàn"),
        ChineseSurname(character: "彭", pinyin: "Péng"),
        ChineseSurname(character: "鲁", pinyin: "Lǔ"),
        ChineseSurname(character: "韦", pinyin: "Wéi"),
        ChineseSurname(character: "昌", pinyin: "Chāng"),
        ChineseSurname(character: "马", pinyin: "Mǎ"),
        ChineseSurname(character: "苗", pinyin: "Miáo"),
        ChineseSurname(character: "凤", pinyin: "Fèng"),
        ChineseSurname(character: "花", pinyin: "Huā"),
        ChineseSurname(character: "方", pinyin: "Fāng"),
        ChineseSurname(character: "俞", pinyin: "Yú"),
        ChineseSurname(character: "任", pinyin: "Rén"),
        ChineseSurname(character: "袁", pinyin: "Yuán"),
        ChineseSurname(character: "柳", pinyin: "Liǔ"),
        ChineseSurname(character: "鲍", pinyin: "Bào"),
        ChineseSurname(character: "史", pinyin: "Shǐ"),
        ChineseSurname(character: "唐", pinyin: "Táng"),
        ChineseSurname(character: "费", pinyin: "Fèi"),
        ChineseSurname(character: "薛", pinyin: "Xuē"),
        ChineseSurname(character: "雷", pinyin: "Léi"),
        ChineseSurname(character: "贺", pinyin: "Hè"),
        ChineseSurname(character: "倪", pinyin: "Ní"),
        ChineseSurname(character: "汤", pinyin: "Tāng"),
        ChineseSurname(character: "殷", pinyin: "Yīn"),
        ChineseSurname(character: "罗", pinyin: "Luó"),
        ChineseSurname(character: "毕", pinyin: "Bì"),
        ChineseSurname(character: "郝", pinyin: "Hǎo"),
        ChineseSurname(character: "安", pinyin: "Ān"),
        ChineseSurname(character: "常", pinyin: "Cháng"),
        ChineseSurname(character: "于", pinyin: "Yú"),
        ChineseSurname(character: "傅", pinyin: "Fù"),
        ChineseSurname(character: "齐", pinyin: "Qí"),
        ChineseSurname(character: "康", pinyin: "Kāng"),
        ChineseSurname(character: "余", pinyin: "Yú"),
        ChineseSurname(character: "元", pinyin: "Yuán"),
        ChineseSurname(character: "顾", pinyin: "Gù"),
        ChineseSurname(character: "孟", pinyin: "Mèng"),
        ChineseSurname(character: "黄", pinyin: "Huáng"),
        ChineseSurname(character: "穆", pinyin: "Mù"),
        ChineseSurname(character: "萧", pinyin: "Xiāo"),
        ChineseSurname(character: "尹", pinyin: "Yǐn"),
        ChineseSurname(character: "姚", pinyin: "Yáo"),
        ChineseSurname(character: "邵", pinyin: "Shào"),
        ChineseSurname(character: "汪", pinyin: "Wāng"),
        ChineseSurname(character: "毛", pinyin: "Máo"),
        ChineseSurname(character: "狄", pinyin: "Dí"),
        ChineseSurname(character: "贝", pinyin: "Bèi"),
        ChineseSurname(character: "明", pinyin: "Míng"),
        ChineseSurname(character: "臧", pinyin: "Zāng"),
        ChineseSurname(character: "成", pinyin: "Chéng"),
        ChineseSurname(character: "戴", pinyin: "Dài"),
        ChineseSurname(character: "宋", pinyin: "Sòng"),
        ChineseSurname(character: "庞", pinyin: "Páng"),
        ChineseSurname(character: "熊", pinyin: "Xióng"),
        ChineseSurname(character: "纪", pinyin: "Jǐ"),
        ChineseSurname(character: "舒", pinyin: "Shū"),
        ChineseSurname(character: "屈", pinyin: "Qū"),
        ChineseSurname(character: "项", pinyin: "Xiàng"),
        ChineseSurname(character: "祝", pinyin: "Zhù"),
        ChineseSurname(character: "董", pinyin: "Dǒng"),
        ChineseSurname(character: "梁", pinyin: "Liáng"),
        ChineseSurname(character: "杜", pinyin: "Dù"),
        ChineseSurname(character: "阮", pinyin: "Ruǎn"),
        ChineseSurname(character: "蓝", pinyin: "Lán"),
        ChineseSurname(character: "闵", pinyin: "Mǐn"),
        ChineseSurname(character: "席", pinyin: "Xí"),
        ChineseSurname(character: "季", pinyin: "Jì"),
        ChineseSurname(character: "贾", pinyin: "Jiǎ"),
        ChineseSurname(character: "黎", pinyin: "Lí"),
        ChineseSurname(character: "段", pinyin: "Duàn"),
        ChineseSurname(character: "雍", pinyin: "Yōng"),
        ChineseSurname(character: "钟", pinyin: "Zhōng"),
        ChineseSurname(character: "徐", pinyin: "Xú"),
        ChineseSurname(character: "邱", pinyin: "Qiū"),
        ChineseSurname(character: "骆", pinyin: "Luò"),
        ChineseSurname(character: "高", pinyin: "Gāo"),
        ChineseSurname(character: "夏", pinyin: "Xià"),
        ChineseSurname(character: "蔡", pinyin: "Cài"),
        ChineseSurname(character: "田", pinyin: "Tián"),
        ChineseSurname(character: "樊", pinyin: "Fán"),
        ChineseSurname(character: "胡", pinyin: "Hú"),
        ChineseSurname(character: "凌", pinyin: "Líng"),
        ChineseSurname(character: "霍", pinyin: "Huò"),
        ChineseSurname(character: "虞", pinyin: "Yú"),
        ChineseSurname(character: "万", pinyin: "Wàn"),
        ChineseSurname(character: "支", pinyin: "Zhī"),
        ChineseSurname(character: "柯", pinyin: "Kē"),
        ChineseSurname(character: "管", pinyin: "Guǎn"),
        ChineseSurname(character: "卢", pinyin: "Lú"),
        ChineseSurname(character: "莫", pinyin: "Mò"),
        ChineseSurname(character: "经", pinyin: "Jīng"),
        ChineseSurname(character: "房", pinyin: "Fáng"),
        ChineseSurname(character: "裘", pinyin: "Qiú"),
        ChineseSurname(character: "缪", pinyin: "Miào"),
        ChineseSurname(character: "解", pinyin: "Xiè"),
        ChineseSurname(character: "宗", pinyin: "Zōng"),
        ChineseSurname(character: "丁", pinyin: "Dīng"),
        ChineseSurname(character: "邓", pinyin: "Dèng"),
        ChineseSurname(character: "林", pinyin: "Lín"),
        ChineseSurname(character: "刁", pinyin: "Diāo"),
        ChineseSurname(character: "石", pinyin: "Shí"),
        ChineseSurname(character: "崔", pinyin: "Cuī"),
        ChineseSurname(character: "吉", pinyin: "Jí"),
        ChineseSurname(character: "钮", pinyin: "Niǔ"),
        ChineseSurname(character: "龚", pinyin: "Gōng"),
        ChineseSurname(character: "程", pinyin: "Chéng"),
        // 常见复姓
        ChineseSurname(character: "欧阳", pinyin: "Ōuyáng"),
        ChineseSurname(character: "司马", pinyin: "Sīmǎ"),
        ChineseSurname(character: "诸葛", pinyin: "Zhūgě"),
        ChineseSurname(character: "上官", pinyin: "Shàngguān"),
        ChineseSurname(character: "尉迟", pinyin: "Yùchí"),
        ChineseSurname(character: "公孙", pinyin: "Gōngsūn"),
        ChineseSurname(character: "夏侯", pinyin: "Xiàhóu"),
        ChineseSurname(character: "皇甫", pinyin: "Huángfǔ"),
        ChineseSurname(character: "慕容", pinyin: "Mùróng"),
        ChineseSurname(character: "东方", pinyin: "Dōngfāng"),
        ChineseSurname(character: "南宫", pinyin: "Nángōng"),
        ChineseSurname(character: "西门", pinyin: "Xīmén")
    ]

    /// 随机抽取 N 个不重复的姓。
    static func randomSample(count: Int) -> [ChineseSurname] {
        Array(all.shuffled().prefix(count))
    }
}
